name: showcase_project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta


dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  l: ^5.0.1
  mask_text_input_formatter: ^2.9.0
  octopus: ^0.0.9
  infinite_scroll_pagination: ^4.0.0
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  padi: ^1.0.2
  easy_debounce: ^2.0.3
  flutter_secure_storage: ^10.0.0
  overlay_notifications:
    git:
      url: https://github.com/GDTuka/overlay_notification.git
  evvm:
    git:
      url: https://github.com/GDTuka/evvm.git
      ref: master
  dio: ^5.9.2
  json_serializable: ^6.13.1
  json_annotation: ^4.11.0
  cached_network_image: ^3.4.1
  wechat_assets_picker: ^10.1.1
  wechat_camera_picker: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
